name: fast_collocation_dictionary
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.5
  flutter_spinkit: ^5.2.0
  # freezed_annotation: ^2.4.1
  # hive: ^2.2.3
  # hive_flutter: ^1.1.0
  # json_annotation: ^4.8.1
  # loader_overlay: ^2.3.2
  riverpod_annotation: ^2.3.0
  uuid: ^4.2.1
  dartx: ^1.2.0
  page_transition: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  custom_lint: ^0.5.6
  flutter_lints: ^2.0.0
  # freezed: ^2.4.5
  # json_serializable: ^6.7.1
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.3


flutter:
  # uses-material-design: true
  assets:
    - assets/images/




  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
